<?php
	// include wp cause it's a standalone page
	require('../../../../wp-blog-header.php');
	require_once('../../../../wp-config.php');
	require_once('../../../../wp-includes/wp-db.php');
	// Load the options
	global $wpdb, $wpms_options, $phpmailer;	
	define('DOMAIN_PLUGIN', 'cheetahsender');
	// WP_MAIL est en mode SMTP
	// Make sure the PHPMailer class has been instantiated 
	if ( !is_object( $phpmailer ) || !is_a( $phpmailer, 'PHPMailer' ) ) 
	{
		require_once '../../../../wp-includes/class-phpmailer.php';
		require_once '../../../../wp-includes/class-smtp.php';
		$phpmailer = new PHPMailer();		
	}

	if (isset($_POST['to'])) 
	{
		// Set up the mail variables
		$to = $_POST['to'];
		$subject = 'CheetahSender for WordPress : ' . $to;
		$message = __('This is a test email generated by the CheetahSender Plugin', DOMAIN_PLUGIN);		
		// Set SMTPDebug to level 2
		$phpmailer->SMTPDebug = 2;		
		// Start output buffering to grab smtp debugging output
		ob_start();
		// Send the test mail
		$result = wp_mail($to,$subject,$message);		
		// Grab the smtp debugging output
		$smtp_debug = ob_get_clean();				
		if(strpos( $smtp_debug,'SERVER:250 2.6.0 message received') && strpos( $smtp_debug,'SERVER:354 send message') ){
			echo 0;
		}else
		{
			print_r( __('<strong>Error message :</strong><br />', 'cheetahsender').  $smtp_debug );
		}
		// Destroy $phpmailer so it doesn't cause issues later
		unset($phpmailer);
	}
	else
	{
	echo -1;
	}
?>